FROM registry.cn-hangzhou.aliyuncs.com/miaomo/node:20.9.0

RUN apt-get update \
&& apt-get install -y --no-install-recommends chromium libfontconfig ttf-wqy-microhei xfonts-wqy \
&& rm -rf /var/lib/apt/lists/* \
&& fc-cache -vf \
&& fc-list
